config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get '/pets', to: 'pets#index', as: :pets
  post '/pets', to: 'pets#create'

  get '/pets/new', to: 'pets#new', as: :new_pet

  get '/pets/:id', to: 'pets#show', as: :pet
  patch '/pets/:id', to: 'pets#update'
  delete '/pets/:id', to: 'pets#destroy'

  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['cat', 'dog', 'hamster', 'rabbit',  'bird']

  validates :color, :location, :found_on, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    (Date.today - self.found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to pets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: :unprocessable_entity
    end

  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private

  # FILTER
  def set_pet
    @pet = Pet.find(params[:id])
  end

  # STRONG PARAMS
  def pet_params
    params.require(:pet).permit(:color, :location, :found_on, :species)
  end
end

# PARAMS
# 1. to access dynamic values from the URL
# 2. to access information that is coming from the form

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :color %>
  <%= f.input :location %>
  <%= f.input :found_on %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit pet</h1>

<%= render 'form', pet: @pet  %>

app/views/pets/index.html.erb
<h1>Lost Kitties</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.color, pet_path(pet) %> <%= link_to 'Remove pet', pet_path(pet), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></li>
  <% end %>
</ul>

<%= link_to 'Report pet', new_pet_path %>

app/views/pets/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1>Report pet:</h1>
      <%= render 'form', pet: @pet  %>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<h1>Lost pet</h1>
<p>Color: <%= @pet.color %></p>
<p>Species: <%= @pet.species %></p>
<p>Location: <%= @pet.location %></p>
<p>Found: <%= pluralize(@pet.found_days_ago, 'day') %> ago</p>

<%= link_to 'Back to all pets', pets_path %> |
<%= link_to "Edit #{@pet.species}", edit_pet_path(@pet) %>